name: Ecorecycle
description: "AI 기반 재활용 분류 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  path_provider: ^2.0.15
  tflite_flutter: ^0.12.1
  image: ^4.5.4
  permission_handler: ^11.0.0

  flutter_tts: ^4.2.3
  lottie: ^3.1.0

  image_picker: ^1.2.1
  intl: ^0.19.0

  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

  youtube_player_flutter: ^9.1.0

  # 지도 관련 패키지
  geolocator: ^9.0.2
  shared_preferences: ^2.5.4
  google_maps_flutter: ^2.3.1
  geocoding: ^2.1.0
  firebase_auth: ^5.7.0
  material_symbols_icons: ^4.2892.0
  google_generative_ai: ^0.4.7
  provider: ^6.1.5+1
  firebase_database: ^11.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/sprout.png
    - assets/spray1.png
    - assets/spray2.png
    - assets/spray3.png
    - assets/dress1.png
    - assets/dress2.png
    - assets/dress3.png
    - assets/dress4.png
    - assets/quiz.png
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/lottie/
    - assets/shop/goods1.png
    - assets/shop/goods2.png
    - assets/shop/goods3.png
    - assets/shop/goods4.png
    - assets/shop/goods5.png
    - assets/shop/goods6.png
    - assets/shop/education1.png
    - assets/shop/education2.png
    - assets/shop/education3.png
    - assets/shop/education4.png
    - assets/shop/education5.png
    - assets/shop/education6.png

